services:
  pg-itp-iam-db:
    image: postgres:17.5-bullseye
    container_name: pg-exstad
    environment:
      POSTGRES_USER: exstad
      POSTGRES_PASSWORD: exstad
      POSTGRES_DB: exstad_db
    ports:
      - "16868:5432"
    volumes:
      - ./init_scripts/pg_itp_iam_init.sql:/docker-entrypoint-initdb.d/pg_itp_iam_init.sql
    networks:
      - itp-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./data:/data
    networks:
      - itp-net
    command: server --console-address ":9001" /data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pg-itp-iam-db:5432/exstad_db
      KC_DB_USERNAME: exstad
      KC_DB_PASSWORD: exstad
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    ports:
      - "8180:8080"
    depends_on:
      - pg-itp-iam-db
    networks:
      - itp-net

networks:
  itp-net:
    external: true